package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name="brands"
    ,catalog="store_market"
)
public class Brands  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String logoPath;
     private Set<Products> productses = new HashSet<Products>(0);

    public Brands() {
    }

    public Brands(String name, String logoPath, Set<Products> productses) {
       this.name = name;
       this.logoPath = logoPath;
       this.productses = productses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="logo_path", length=100)
    public String getLogoPath() {
        return this.logoPath;
    }
    
    public void setLogoPath(String logoPath) {
        this.logoPath = logoPath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="brands")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


