package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Branches generated by hbm2java
 */
@Entity
@Table(name="branches"
    ,catalog="store_market"
)
public class Branches  implements java.io.Serializable {


     private Integer id;
     private Zones zones;
     private String building;
     private String streetName;
     private Date workingStart;
     private Date workingEnd;
     private String telephone;

    public Branches() {
    }

    public Branches(Zones zones, String building, String streetName, Date workingStart, Date workingEnd, String telephone) {
       this.zones = zones;
       this.building = building;
       this.streetName = streetName;
       this.workingStart = workingStart;
       this.workingEnd = workingEnd;
       this.telephone = telephone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zone_id", nullable=false)
    public Zones getZones() {
        return this.zones;
    }
    
    public void setZones(Zones zones) {
        this.zones = zones;
    }

    
    @Column(name="building", nullable=false, length=100)
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }

    
    @Column(name="street_name", nullable=false, length=100)
    public String getStreetName() {
        return this.streetName;
    }
    
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="working_start", nullable=false, length=8)
    public Date getWorkingStart() {
        return this.workingStart;
    }
    
    public void setWorkingStart(Date workingStart) {
        this.workingStart = workingStart;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="working_end", nullable=false, length=8)
    public Date getWorkingEnd() {
        return this.workingEnd;
    }
    
    public void setWorkingEnd(Date workingEnd) {
        this.workingEnd = workingEnd;
    }

    
    @Column(name="telephone", nullable=false, length=20)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }




}


