package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catagories generated by hbm2java
 */
@Entity
@Table(name="catagories"
    ,catalog="store_market"
)
public class Catagories  implements java.io.Serializable {


     private String id;
     private String name;
     private String decription;
     private Set<Products> productses = new HashSet<Products>(0);

    public Catagories() {
    }

	public Catagories(String name){
        this.name=name;
        
        }
    public Catagories(String id, String name) {
        this.id = id;
        this.name = name;
    }
    public Catagories(String id, String name, String decription, Set<Products> productses) {
       this.id = id;
       this.name = name;
       this.decription = decription;
       this.productses = productses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=45)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="decription", length=65535)
    public String getDecription() {
        return this.decription;
    }
    
    public void setDecription(String decription) {
        this.decription = decription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catagories")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


