package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductSizes generated by hbm2java
 */
@Entity
@Table(name="product_sizes"
    ,catalog="store_market"
)
public class ProductSizes  implements java.io.Serializable {


     private Integer id;
     private Products products;
     private Sizes sizes;
     private Integer quantity;
     private Float price;

    public ProductSizes() {
    }

	
    public ProductSizes(Products products, Sizes sizes) {
        this.products = products;
        this.sizes = sizes;
    }
    public ProductSizes(Products products, Sizes sizes, Integer quantity, Float price) {
       this.products = products;
       this.sizes = sizes;
       this.quantity = quantity;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="size_id", nullable=false)
    public Sizes getSizes() {
        return this.sizes;
    }
    
    public void setSizes(Sizes sizes) {
        this.sizes = sizes;
    }

    
    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", precision=12, scale=0)
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }




}


