package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="store_market"
)
public class Products  implements java.io.Serializable {


     private Integer id;
     private Brands brands;
     private Catagories catagories;
     private String name;
     private String description;
     private String picturePath;
     private Set<ProductSizes> productSizeses = new HashSet<ProductSizes>(0);

    public Products() {
    }

	
    public Products(Brands brands, Catagories catagories, String name) {
        this.brands = brands;
        this.catagories = catagories;
        this.name = name;
    }
    public Products(Brands brands, Catagories catagories, String name, String description, String picturePath, Set<ProductSizes> productSizeses) {
       this.brands = brands;
       this.catagories = catagories;
       this.name = name;
       this.description = description;
       this.picturePath = picturePath;
       this.productSizeses = productSizeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="brand_id", nullable=false)
    public Brands getBrands() {
        return this.brands;
    }
    
    public void setBrands(Brands brands) {
        this.brands = brands;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="catagory_id", nullable=false)
    public Catagories getCatagories() {
        return this.catagories;
    }
    
    public void setCatagories(Catagories catagories) {
        this.catagories = catagories;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="picture_path", length=100)
    public String getPicturePath() {
        return this.picturePath;
    }
    
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<ProductSizes> getProductSizeses() {
        return this.productSizeses;
    }
    
    public void setProductSizeses(Set<ProductSizes> productSizeses) {
        this.productSizeses = productSizeses;
    }




}


