package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sizes generated by hbm2java
 */
@Entity
@Table(name="sizes"
    ,catalog="store_market"
)
public class Sizes  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<ProductSizes> productSizeses = new HashSet<ProductSizes>(0);

    public Sizes() {
    }

    public Sizes(String name, Set<ProductSizes> productSizeses) {
       this.name = name;
       this.productSizeses = productSizeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sizes")
    public Set<ProductSizes> getProductSizeses() {
        return this.productSizeses;
    }
    
    public void setProductSizeses(Set<ProductSizes> productSizeses) {
        this.productSizeses = productSizeses;
    }




}


