package com.seniorsteps.storemarket.dal.hibernate.entity;
// Generated Feb 6, 2023 1:14:50 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zones generated by hbm2java
 */
@Entity
@Table(name="zones"
    ,catalog="store_market"
)
public class Zones  implements java.io.Serializable {


     private Integer id;
     private Cities cities;
     private String name;
     private Set<Branches> brancheses = new HashSet<Branches>(0);

    public Zones() {
    }

	
    public Zones(Cities cities, String name) {
        this.cities = cities;
        this.name = name;
    }
    public Zones(Cities cities, String name, Set<Branches> brancheses) {
       this.cities = cities;
       this.name = name;
       this.brancheses = brancheses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="citie_id", nullable=false)
    public Cities getCities() {
        return this.cities;
    }
    
    public void setCities(Cities cities) {
        this.cities = cities;
    }

    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zones")
    public Set<Branches> getBrancheses() {
        return this.brancheses;
    }
    
    public void setBrancheses(Set<Branches> brancheses) {
        this.brancheses = brancheses;
    }




}


